### ISSUE TITLE
dist directory not creating.

### ISSUE THREAD

**Issue by okayjeffrey** [joejoinerr/tumblr-boilerplate#1]
I am a total newb to grunt, but when running `$ grunt` or `$ grunt` build, and it does not create the `dist/` directory like it says... I have been poking around but have not found the issue yet `grunt-html-build` is there.

I don't know whats wrong. :/ Please help and thanks for the boilerplate!

**Comment by joejoinerr** [comment]
Thanks for reaching out @okayjeffrey. I thought this would be a config bug I'd overlooked but in fact you just have to run `$ grunt dist`. The `build` function now just compiles the Sass. I'll update the docs.

**Comment by okayjeffrey** [comment]
Thanks!!!
